export const courses = [
  {
    id: "1",
    courseName: "Introduction to Coding",
    description: "Learn the basics of coding in this beginner-friendly course.",
    price: "19.99",
    category: "code",
  },
  {
    id: "2",
    courseName: "Chemistry Fundamentals",
    description:
      "Explore the foundational concepts of chemistry in this course.",
    price: "29.99",
    category: "science",
  },
  {
    id: "3",
    courseName: "Art History",
    description: "Discover the history of art and its impact on culture.",
    price: "24.99",
    category: "art",
  },
  {
    id: "4",
    courseName: "Business Management Essentials",
    description: "Learn essential business management skills for success.",
    price: "39.99",
    category: "business",
  },
  {
    id: "5",
    courseName: "JavaScript Basics",
    description: "Get started with JavaScript programming language.",
    price: "19.99",
    category: "code",
  },
  {
    id: "6",
    courseName: "Introduction to Biology",
    description: "Explore the basics of biology in this introductory course.",
    price: "29.99",
    category: "science",
  },
  {
    id: "7",
    courseName: "Drawing Fundamentals",
    description: "Learn the basic techniques of drawing in this course.",
    price: "24.99",
    category: "art",
  },
  {
    id: "8",
    courseName: "Marketing Principles",
    description: "Discover the fundamental principles of marketing.",
    price: "39.99",
    category: "business",
  },
  {
    id: "9",
    courseName: "Python Programming",
    description: "Learn Python programming language from scratch.",
    price: "19.99",
    category: "code",
  },
  {
    id: "10",
    courseName: "Physics Fundamentals",
    description: "Explore the basic principles of physics in this course.",
    price: "29.99",
    category: "science",
  },
  {
    id: "11",
    courseName: "Oil Painting Techniques",
    description: "Learn advanced oil painting techniques in this course.",
    price: "24.99",
    category: "art",
  },
  {
    id: "12",
    courseName: "Financial Accounting Basics",
    description: "Learn the basics of financial accounting for business.",
    price: "39.99",
    category: "business",
  },
  {
    id: "13",
    courseName: "React.js Essentials",
    description: "Learn the essentials of React.js for web development.",
    price: "19.99",
    category: "code",
  },
  {
    id: "14",
    courseName: "Environmental Science",
    description: "Explore environmental issues and solutions in this course.",
    price: "29.99",
    category: "science",
  },
  {
    id: "15",
    courseName: "Sculpture Basics",
    description: "Learn the basics of sculpture in this introductory course.",
    price: "24.99",
    category: "art",
  },
];

// code science fun art business
